sudo: false

language: node_js

node_js:
  - 6
  - 8
  - 10

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - yarn global add nyc codecov

script:
  - yarn lint
  - yarn test

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
